all:
  children:
    router:
      hosts:
        192.168.1.1
      vars:
        ansible_python_interpreter: /usr/bin/python
    nas:
      hosts:
        192.168.1.2:
      vars:
        ansible_python_interpreter: /usr/local/bin/python
    raspberrypi:
      hosts:
        192.168.1.4:
        192.168.1.5:
      vars:
        ansible_python_interpreter: /usr/bin/python
    pihole:
      children:
        raspberrypi:
