all:
  children:
    raspberrypi:
      hosts:
        192.168.1.4:
        192.168.1.5:
    pihole:
      children:
        raspberrypi:
    router:
      hosts:
        192.168.1.1
    nas:
      hosts:
        192.168.1.2:
      vars:
        ansible_python_interpreter: /usr/local/bin/python
